
services:
  flask:
    build:
      context: .
      dockerfile: flask_dockerfile
#    volumes:
#      - ./logs:/app/logs
    expose:
      - "5000"

  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
    ports:
      - "8080:80"
      - "8443:8443"
    depends_on:
      - flask
